
project_id = "mpvtaqslxfjvvzcnhcjs"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 54322

[studio]
enabled = true
port = 54323

[inbucket]
enabled = true
port = 54324

[[functions.create-subscription-checkout]]
verify_jwt = true

[[functions.check-subscription]]
verify_jwt = true

[[functions.customer-portal]]
verify_jwt = true
