// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mpvtaqslxfjvvzcnhcjs.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1wdnRhcXNseGZqdnZ6Y25oY2pzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg5MDIzMjcsImV4cCI6MjA2NDQ3ODMyN30.nJw7cuGPipERs-4_VFicrbpSmzbXNC7Uh6qps3Nwj5Y";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);